name: Update Playlist
on:
  schedule:
    - cron: "0 */4 * * *"  # Runs every 4 hours
  workflow_dispatch:        # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install google-api-python-client requests
      - name: Run script
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python youtube_automation.py